set JAVA_HOME=C:\Users\guany\.jdks\ms-17.0.18
set CHATAGENT_DB_PASSWORD=app123
set CHATAGENT_DB_URL=jdbc:postgresql://localhost:5432/chatagent
set CHATAGENT_DB_USERNAME=app
set CHATAGENT_DEEPSEEK_API_KEY=REDACTED_API_KEY
set CHATAGENT_DEEPSEEK_BASE_URL=https://api.deepseek.com
set CHATAGENT_DEEPSEEK_MODEL=deepseek-chat
set CHATAGENT_REDIS_PASSWORD=123456
set CHATAGENT_RAG_VECTOR_STORE_PROVIDER=milvus
set CHATAGENT_MILVUS_ENABLED=true
set CHATAGENT_MILVUS_HOST=localhost
set CHATAGENT_MILVUS_PORT=19530
set CHATAGENT_MILVUS_DATABASE=default
set CHATAGENT_MILVUS_COLLECTION=chat_file_chunk
set CHATAGENT_MILVUS_KNOWLEDGE_BASE_COLLECTION=chat_knowledge_chunk
set CHATAGENT_MILVUS_METRIC_TYPE=COSINE
set CHATAGENT_MILVUS_INDEX_TYPE=AUTOINDEX
set CHATAGENT_MILVUS_CONSISTENCY_LEVEL=BOUNDED
set CHATAGENT_MILVUS_DIMENSION=1024
set CHATAGENT_RAG_EMBEDDING_BASE_URL=http://localhost:11434
set CHATAGENT_RAG_EMBEDDING_MODEL=bge-m3:latest
cd /d C:\Users\guany\OneDrive - Nanyang Technological University\??\ChatAgent\chatagent
call .\mvnw.cmd -o -pl bootstrap spring-boot:run
